# WARNING!!!! PyYAML resolves scientific notation numbers as strings-
# e.g. 1.6e3 is interpreted as '1.6e3', not 1600. These numbers should
# be expanded (see bc_Te_max)

emission_lines:
    el_narrow_min: 100 #km/s
    el_narrow_max: 1000 #km/s
    el_broad_min: 1000 #km/s
    el_broad_max: 12000 #km/s
    el_shift: 5000 #km/s
    el_prefit: False#True#
    el_prefit_window: 15000 #km/s
## Host Galaxy parameters##
host_galaxy:
    boxcar_width: 5
    hg_models: "../Data/HostModels"
    hg_norm_min: 0.
    hg_norm_max: "max_flux"
    hg_stellar_disp_min: 30. # km/s. Must be dispersion, not FWHM
    hg_stellar_disp_max: 1000. # km/s. Must be dispersion, not FWHM
    hg_template_stellar_disp: 0.0
    hg_kernel_size_sigma: 10 # pixels

## Boxcar width to use when calculating running mean ##
boxcar_width: 5

## NuclearContnuumComponent power law parameters ##
## WARNING: If using broken power law, need to have estimation of priors otherwise model cannot converge ##
nuclear_continuum:
    boxcar_width: 5
    broken_pl: False
    pl_slope_min: -3.
    pl_slope_max: 3.
    pl_norm_min: 0.
    pl_norm_max: "fnw" #max_flux or fnw
    pl_wave_break_min: "min_wl"
    pl_wave_break_max: "max_wl"
    #pl_par_prior: np.random.uniform

## Balmer Continuum ##
balmer_continuum:
    bc_line_type: "lorentzian" #or "gaussian"
    bc_lines_min: 3. #km/s
    bc_lines_max: 400. #km/s
    bc_norm_min: 0.
    bc_norm_max: "bcmax_flux" # Balmer Continuum max flux
    bc_Te_min: 500.
    bc_Te_max: 100000.
    bc_tauBE_min: 0.
    bc_tauBE_max: 2.
    bc_loffset_min: -10.
    bc_loffset_max: 10.
    bc_lwidth_min: 100.
    bc_lwidth_max: 10000.
    bc_logNe_min: 2
    bc_logNe_max: 9


## Fe Component ##
fe_forest:
    boxcar_width: 10
    fe_templates: "../Data/FeModels" #"/user/jotaylor/git/spamm/Data/testmodels"
    fe_template_width: 900. #km/s
    fe_norm_min: 0.
    fe_norm_max: "fnw" #max_flux or fnw
    fe_width_min: 901. # km/s (FWHM)
    fe_width_max: 10000. # km/s (FWHM)
    fe_line_type: "gaussian" # or "lorentzian"
    fe_kernel_size_sigma: 3 # pixels

## Flux Conserving Binning ##
rebin_spec: False

## Testing ##
testing:
    wl_min: 1000
    wl_max: 10000
    wl_step: 0.5
